name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        KEY_FILE: ${{ secrets.KEY_FILE }}

      run: |
        echo "${{ secrets.KEY_FILE }}" > Intern.pem
        chmod 700 Intern.pem
        ssh -o StrictHostKeyChecking=no -i Intern.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /root/nest-hello-world

          git pull origin master
          npm install
          npm run build
          sudo service nginx restart
        EOF

